config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: %i[new create]
  end
  resources :reviews, only: %i[destroy show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORIES = %w[chinese italian japanese french belgian]
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
  validates :category, inclusion: { in: CATEGORIES }
end

# When a restaurant is destroyed, all of its reviews must be destroyed as well.

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, presence: true
  validates :rating, numericality: true
  validates :rating, inclusion: { in: (0..5) }
  validates :content, presence: true
end

# content cannot be blank (FAILED - 2)
#   rating cannot be blank (FAILED - 3)
#   parent restaurant cannot be nil
#   rating should be an integer (FAILED - 4)
#   rating should be a number between 0 and 5 (FAILED - 5)

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else render :new
    end
  end

  # def destroy
  #   @restaurant = Restaurant.find(params[:id])
  #   @restaurant.destroy
  #   redirect_to restaurants_path
  # end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1> Our Restaurants </h1>
<ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= link_to restaurant.name, restaurant_path(restaurant.id) %></li>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
<h1>Create a new restaurant</h1>

<%= form_for (@restaurant) do |t| %>
  <%= t.label :name %>
  <%= t.text_field :name %>
  <%= t.label :address %>
  <%= t.text_field :address %>
  <%= t.label :phone_number %>
  <%= t.text_field :phone_number %>
  <%= t.label :category %>
  <%= t.text_field :category %>
  <%= t.submit %>
<% end %>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.title %></h2>
<p><%= @restaurant.details %></p>
<p><%= @restaurant.completed %></p>

<%= link_to "edit", restaurant_edit_path(@restaurant) %>
<%= link_to "Delete #{@restaurant.name}",
              restaurant_path(@restaurant),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>

app/views/reviews/new.html.erb
<h1>Create a new review</h1>

<%= form_for (@restaurant) do |t| %>
  <%= t.label :rating %>
  <%= t.text_field :rating %>
  <%= t.label :content%>
  <%= t.text_field :content%>
  <%= t.submit %>
<% end %>